Repository WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P3-Street-Art-Hunter, pull requests merged in 2024-09, with the labels that each got.

#8 Us01 path
  server/app/controllers/ArtworkActions.js
  server/app/controllers/CityActions.js
  server/app/controllers/FavoriteActions.js
  server/app/controllers/StyleActions.js
  server/app/controllers/UserActions.js
  server/app/router.js
  server/database/models/ArtworkRepository.js
  server/database/models/CityRepository.js
  server/database/models/FavoriteRepository.js
  server/database/models/StyleRepository.js
  server/database/models/UserRepository.js
  server/database/schema.sql
  server/package.json
Labels: CHANGES REQUESTED, CONFLICTS, CORRECTIONS DONE

#28 Us01 user register
  client/src/App.jsx
  client/src/assets/images/closeEyes.svg
  client/src/assets/images/openEyes.svg
  client/src/components/GradientButton.jsx
  client/src/main.jsx
  client/src/pages/Gallery.jsx
  client/src/pages/Register.jsx
  client/src/styles/connection.css
  client/src/styles/register.css
Labels: REVIEWED

#27 Us02 user navigation
  client/package.json
  client/src/assets/images/locationAnim.json
  client/src/components/NavBar.jsx
  client/src/styles/navBar.css
  server/app/controllers/UserActions.js
Labels: REVIEWED

#29 Us02 user location
  client/src/App.jsx
  client/src/assets/images/backgroundDesktop.svg
  client/src/assets/images/couronneLogo.svg
  client/src/assets/images/simpleLogo.svg
  client/src/components/Map.jsx
  client/src/components/NavBar.jsx
  client/src/components/desktop/NavBarDesktop.jsx
  client/src/main.jsx
  client/src/pages/Gallery.jsx
  client/src/pages/HomeDesktop.jsx
  client/src/styles/navBar.css
  client/src/styles/styleHome.css
  client/src/styles/styleRanking.css
  client/src/utils/hook/useScreenWidth.jsx
  package-lock.json
Labels: REVIEWED

#30 Us01 user register
  client/src/pages/Register.jsx
  client/src/styles/register.css
  server/database/schema.sql
Labels: REVIEWED

#33 Us01 user connection
  client/src/assets/images/camera_take_picture.svg
  client/src/main.jsx
  client/src/pages/Camera.jsx
  client/src/pages/Connection.jsx
  client/src/services/request.js
  client/src/styles/camera.css
  server/app/controllers/ArtworkActions.js
  server/app/router.js
  server/app/services/auth.js
  server/database/schema.sql
Labels: CHANGES REQUESTED, REVIEWED

#34 Added css responsive for llogin page 🤖
  client/src/components/desktop/NavBarDesktop.jsx
  client/src/pages/Connection.jsx
  client/src/styles/connection.css
Labels: REVIEWED

#35 Css for connection 👍
  client/src/pages/Connection.jsx
  client/src/styles/connection.css
Labels: REVIEWED

#36 Us02 user navigation
  client/src/App.jsx
  client/src/components/NavBar.jsx
  client/src/components/ProfileForm.jsx
  client/src/components/desktop/NavBarDesktop.jsx
  client/src/pages/Connection.jsx
  client/src/pages/HomeDesktop.jsx
  client/src/pages/Profile.jsx
  client/src/services/context/UserInfoContext.jsx
  client/src/services/request.js
  client/src/styles/navBar.css
  client/src/styles/profile.css
  client/src/styles/styleHome.css
  server/app/controllers/authActions.js
  server/app/router.js
  server/app/services/auth.js
  server/app/services/compareLogin.js
Labels: REVIEWED

#38 Us01 admin
  client/src/components/AdminSettings.jsx
  client/src/components/ProfileForm.jsx
  client/src/components/desktop/NavBarDesktop.jsx
  client/src/main.jsx
  client/src/pages/Gestion.jsx
  client/src/pages/GestionDetails.jsx
  client/src/services/request.js
  client/src/styles/galleryDetails.css
  client/src/styles/gestion.css
  client/src/styles/profile.css
  server/app/controllers/ArtworkActions.js
  server/app/router.js
  server/database/models/ArtworkRepository.js
  server/database/schema.sql
Labels: REVIEWED

#42 Us01 admin
  client/src/components/AdminSettings.jsx
  client/src/main.jsx
  client/src/pages/GestionDetails.jsx
  client/src/pages/UserDetails.jsx
  client/src/styles/gestion.css
  client/src/styles/gestionDetails.css
  client/src/styles/userDetails.css
Labels: REVIEWED

#43 Us01 user connection
  client/.env.sample
  client/src/assets/images/circlePin.png
  client/src/assets/images/pinArt.png
  client/src/assets/images/streetBg.webp
  client/src/components/CameraForm.jsx
  client/src/components/GradientButton.jsx
  client/src/components/Map.jsx
  client/src/main.jsx
  client/src/pages/Camera.jsx
  client/src/pages/Connection.jsx
  client/src/pages/Register.jsx
  client/src/services/context/GeoLocationContext.jsx
  client/src/services/request.js
  client/src/styles/camera.css
  client/src/utils/cameraTools.js
  server/app/controllers/ArtworkActions.js
  server/app/router.js
  server/app/services/upload.js
  server/app/services/verifyMiddleware.js
  server/database/models/ArtworkRepository.js
  server/database/schema.sql
  server/public/uploads/.gitkeep
  server/public/uploads/1a301ae6-715b-45bd-84e0-a87e826f1657.jpg
  server/public/uploads/2373f96c-9238-4045-a1e6-0764face7f8d
  server/public/uploads/3ba3e891-70ed-4028-8588-7bf50b27fb52
  server/public/uploads/494b70bf-63a8-4866-9a37-a4d5f55c27cd.jpg
  server/public/uploads/4c51cc11-c9fb-423a-aa7b-081e0df40dc1.png
  server/public/uploads/5ccca4aa-a196-4230-ad88-80d05d01ee2a.png
  server/public/uploads/5e85f4d4-ca64-43c8-aaa8-d36eedfc558a.jpg
  server/public/uploads/64450137-8b5b-4b38-9a92-d6246ae057c3
  server/public/uploads/657ee659-b801-4d1b-827c-7cdd77e344b2.jpg
  server/public/uploads/832631c5-372d-455d-b454-cbba10b05d6a
  server/public/uploads/d1051e11-1397-4d4b-8577-d00215119c68
  server/public/uploads/e5e9e2ac-f73b-4a87-89fd-289941133adf.png
  server/public/uploads/f25a4d76-f5cb-417c-955f-69091078e0b6.jpg
  server/public/uploads/f75b3ff6-435c-40bc-ad9f-dc3d75e77c6b.png
  server/public/uploads/fa97e303-5ec6-48df-9fdb-8bb416809ba8.png
  server/public/uploads/fd66b125-5c98-4ef3-ad27-1e340d792249
Labels: REVIEWED

#44 Us03 profile update avatar
  client/src/assets/images/locationAnim.json
  client/src/components/ProfileForm.jsx
  client/src/pages/Profile.jsx
  client/src/services/dataProfile.js
  client/src/services/request.js
  server/app/config.js
  server/app/services/verifyMiddleware.js
  server/public/uploads/avatars/15020057-528c-4639-b9bc-5875748fe69f.jpg
  server/public/uploads/avatars/308b2f60-3449-42d4-b5f0-472c2e32c0cc.jpg
  server/public/uploads/avatars/3c77d9c7-5ff0-4a7b-a793-cda30f3b62a0.jpg
  server/public/uploads/avatars/5c4fdb7d-ea51-4fb8-b0f7-847db6431848.png
  server/public/uploads/avatars/afd3ffea-0864-432d-9d5f-e6426bdd994a.jpg
  server/public/uploads/avatars/f1e55ca7-762d-4080-8e77-e043921029ad.jpg
Labels: REVIEWED

#46 Us02 favorites
  client/index.html
  client/src/components/ArtworkDetails.jsx
  client/src/components/CameraForm.jsx
  client/src/components/GradientButton.jsx
  client/src/main.jsx
  client/src/pages/Camera.jsx
  client/src/pages/Favorites.jsx
  client/src/pages/GalleryDetails.jsx
  client/src/pages/Home.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Ranking.jsx
  client/src/services/request.js
  client/src/styles/profile.css
  client/src/styles/styleArtworkDetail.css
  client/src/styles/styleFavorites.css
  client/src/styles/styleHome.css
  server/app/controllers/FavoriteActions.js
  server/app/services/verifyMiddleware.js
  server/database/models/FavoriteRepository.js
  server/public/uploads/0d537046-e063-4b9d-99f2-06506ad152ba.png
  server/public/uploads/293f0801-2e89-4d1d-8437-f33232f2af12.png
  server/public/uploads/4d90a09c-5e06-479e-b712-11da4eaf2b02.png
Labels: REVIEWED

#47 :lipstick:Modification of database, artworks tables: addition of real…
  client/src/components/ArtworkDetails.jsx
  server/app/config.js
  server/database/schema.sql
  server/public/uploads/artwork_ciclope.jpeg
  server/public/uploads/artwork_denoyez.jpeg
  server/public/uploads/artwork_interdit.jpg
  server/public/uploads/artwork_kissing.jpg
  server/public/uploads/artwork_monsieurChat.jpg
  server/public/uploads/artwork_pixel.webp
  server/public/uploads/artwork_pixel2.webp
  server/public/uploads/artwork_rencontreFurtive.jpg
  server/public/uploads/artwork_wheatpaste.webp
  server/public/uploads/artwork_yarnBombing.png
  server/public/uploads/artwork_yarnBombing2.webp
  server/public/uploads/avatars/b89dc4ee-9286-40a7-a366-6b308d5ed7e0.png
  server/public/uploads/avatars/d69f96e8-24e5-482b-9dc5-2cfc938d52cd.png
  server/public/uploads/avatars/fa97e303-5ec6-48df-9fdb-8bb416809ba8.png
  server/public/uploads/fa97e303-5ec6-48df-9fdb-8bb416809ba8.png
Labels: CONFLICTS RESOLVED, REVIEWED

#48 Us03 fix upload frontend
  client/.env.sample
  client/src/components/ProfileForm.jsx
  client/src/pages/Gallery.jsx
  client/src/services/request.js
  server/app/config.js
  server/app/controllers/UserActions.js
  server/app/router.js
  server/app/services/verifyMiddleware.js
  server/public/uploads/2373f96c-9238-4045-a1e6-0764face7f8d
  server/public/uploads/3ba3e891-70ed-4028-8588-7bf50b27fb52
  server/public/uploads/4c51cc11-c9fb-423a-aa7b-081e0df40dc1.png
  server/public/uploads/64450137-8b5b-4b38-9a92-d6246ae057c3
  server/public/uploads/832631c5-372d-455d-b454-cbba10b05d6a
  server/public/uploads/avatars/21526e18-0363-4386-8a25-7c990ab5acf4.png
  server/public/uploads/avatars/308b2f60-3449-42d4-b5f0-472c2e32c0cc.jpg
  server/public/uploads/avatars/5c4fdb7d-ea51-4fb8-b0f7-847db6431848.png
  server/public/uploads/avatars/688f5eec-8f40-498c-b78c-e651c1a126e1.png
  server/public/uploads/avatars/afd3ffea-0864-432d-9d5f-e6426bdd994a.jpg
  server/public/uploads/avatars/f1e55ca7-762d-4080-8e77-e043921029ad.jpg
  server/public/uploads/d1051e11-1397-4d4b-8577-d00215119c68
  server/public/uploads/e5e9e2ac-f73b-4a87-89fd-289941133adf.png
  server/public/uploads/f75b3ff6-435c-40bc-ad9f-dc3d75e77c6b.png
  server/public/uploads/fd66b125-5c98-4ef3-ad27-1e340d792249
Labels: REVIEWED

#49 Us01 admin
  client/src/components/AdminSettings.jsx
  client/src/main.jsx
  client/src/pages/Gestion.jsx
  client/src/pages/GestionDetails.jsx
  client/src/pages/UserDetails.jsx
  client/src/services/request.js
  client/src/styles/gestion.css
  client/src/styles/gestionDetails.css
  server/app/controllers/ArtworkActions.js
  server/database/models/ArtworkRepository.js
Labels: REVIEWED

#51 Us01 user register
  client/src/components/desktop/NavBarDesktop.jsx
  client/src/pages/Register.jsx
  client/src/services/request.js
  client/src/styles/register.css
Labels: REVIEWED

#50 Us04 user artwork picture
  client/.env.sample
  client/src/components/ArtworkDetails.jsx
  client/src/pages/Favorites.jsx
  client/src/pages/Gallery.jsx
  client/src/pages/GalleryDetails.jsx
  client/src/pages/Profile.jsx
  client/src/services/request.js
  client/src/styles/styleFavorites.css
  server/app/config.js
Labels: REVIEWED

#53 Us04 user artwork picture
  client/.env.sample
  client/src/assets/favicon.ico
  client/src/components/AdminSettings.jsx
  client/src/components/ArtworkDetails.jsx
  client/src/components/Helpers.jsx
  client/src/components/ProfileForm.jsx
  client/src/pages/Camera.jsx
  client/src/pages/Connection.jsx
  client/src/pages/Favorites.jsx
  client/src/pages/Gallery.jsx
  client/src/pages/GalleryDetails.jsx
  client/src/pages/Gestion.jsx
  client/src/pages/GestionDetails.jsx
  client/src/pages/Help.jsx
  client/src/pages/Home.jsx
  client/src/pages/HomeDesktop.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Ranking.jsx
  client/src/services/request.js
  client/src/styles/gallery.css
  client/src/styles/styleArtworkDetail.css
  server/.env.sample
  server/app/config.js
  server/database/models/ArtworkRepository.js
  server/database/schema.sql
  server/public/uploads/1c4e4782-2ddf-447d-ac06-b5d3bff9adde.png
  server/public/uploads/3e5bc96a-a736-4842-98b4-19b4f8c6aedd.png
  server/public/uploads/513dabfa-2906-4170-a9c8-601f796a4eb5.png
  server/public/uploads/8bda1837-80fa-4ef0-9223-3f9a43960598.png
  server/public/uploads/a862eb7b-0883-4f56-80c1-b90b8c26a701.png
  server/public/uploads/avatars/defaultAvatar.png
Labels: REVIEWED

#55 Us04 app details
  client/src/components/ProfileForm.jsx
  client/src/services/request.js
  server/app/controllers/UserActions.js
  server/app/controllers/authActions.js
  server/app/router.js
  server/app/services/verifyMiddleware.js
  server/database/models/UserRepository.js
  server/public/uploads/avatars/585fa726-b4cc-449a-beca-1fd9b89b9511.png
Labels: REVIEWED
